### ISSUE TITLE
[Request] 2.4.0 update

### ISSUE THREAD

**Issue by abaschen** [MAVProxyUser/PixyElks-SkyPixel-#1]
Hi,

Sorry can't contact you anywhere else...
I'm trying to decompile the latest DJIGo app because they encrypt the flight records now and I would like to decrypt it and so I did but after thorough research I'm stuck at the encryption method.
I've reversed the encryption lib which is a shared object but the expected key doesn't match the one I find when I use my reversed function to compute it. We are like 5 on this problem but stuck at the same place.
could you help?
the class is dji.pilot.fpv.model.h after decompile. 

thx

**Comment by MAVProxyUser** [comment]
Sorry brother... I have all but abandoned this work.

**Comment by abaschen** [comment]
Thanks for the reply. we found it out anyway ;) cheers

**Comment by skylow48** [comment]
Hello TecHunter,

Did you succeed in retrieving the FlightRecord in TXT ? The URL doesn't works anymore : 
http://54.243.252.105:9090/flight/download

Thanks
